[theme]
# Primary accent color for
primaryColor = "#d33682"

# Background color
backgroundColor = "#002b36"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#586e75"

#color used for almost all text
textColor = "#fff"